version: "3"
services:
  slack-jc-sudo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:3000"
    environment:
      - JUMPCLOUD_API_KEY=
      - SLACK_SIGNING_SECRET=
      - SLACK_BOT_USER_TOKEN=
      - SLACK_ADMIN_CHANNEL=